name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.5

      - name: cache replays
        uses: actions/cache@v4
        with:
          path: '**/replays'
          key: replays

      - name: get dependencies
        run: go mod download

      - name: run tests
        run: make test

      - name: notify slack
        if: always()
        uses: jcoene/slack-notify-action@v1
        with:
          job_name: test
          job_status: ${{ job.status }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
